### ISSUE TITLE
DemoApp: dependencies issue

### ISSUE THREAD

**Issue by CharlesJQuarra** [react-native-material-design/react-native-material-design#118]
Just fresh from cloning this repo the problem becomes apparent:

`npm install`

```
<lots of packages are installed, with an error at the end:>
npm WARN react-native-android-statusbar@0.1.3 requires a peer of react-native@>= 0.30.0 but none was installed.
```

**Comment by Salakar** [comment]
RN version on the demo repo needs updating, we'll get round to it sometime - should fix this issue on the demo app.

**Comment by CharlesJQuarra** [comment]
what is the last working version? since master is broken for the time being, do you have a commit hash that is known to work? I didn't see any branches or tags on the repo

**Comment by CharlesJQuarra** [comment]
I tried modifying the `package.json` to previous versions of dependencies, and also adding `react`, which seems to be a dependency of `react-native`, but for some reason it is missing on the demo-app repo. These are the ones I tried:

```
"react": "15.1.0",
"react-native": "0.27.0",
"react-native-action-button": "^1.0.8",
"react-native-android-statusbar": "0.1.2",
"react-native-material-design": "git+https://github.com/react-native-material-design/react-native-material-design.git"
```
[here](http://pasteboard.co/glEDjwASK.png) is the link of the "requiring module 627" error screenshot.

**Comment by ammichael** [comment]
Guys, I'm having dependencies issues too: 

```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/michael/dev/demo-app/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/michael/dev/demo-app/node_modules/react-native/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (/Users/michael/dev/demo-app/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:132:13)
    at /Users/michael/dev/demo-app/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:103:28
    at tryCallOne (/Users/michael/dev/demo-app/node_modules/promise/lib/core.js:37:12)
    at /Users/michael/dev/demo-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/michael/dev/demo-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
~
```

I've tried to update rn to 0.18.1 (read something about this version fixing dupe fbjs) and install react as a dependency, but no lucky too.

**Comment by shivam17** [comment]
@Salakar when will the package.json be corrected? We are facing a lot of issues.

**Comment by shivam17** [comment]
@ammichael facing this exact issue too.

**Comment by shivam17** [comment]
@CharlesJQuarra are you not facing this issue on using the dependencies you mentioned:

demo-app/android/app/src/main/java/com/demoapp/MainActivity.java:32: error: constructor StatusBarPackage in class StatusBarPackage cannot be applied to given types;
                .addPackage(new StatusBarPackage())
                            ^
  required: Activity
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED
