### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by GAVISHSETHI** [react-native-material-design/react-native-material-design#175]
after installing material design create react-native-app project it throws this error

xdl/src/Project.js:920
  let path = parts[1].replace(/`: Module .*/, '').replace(/`/, '').trim();
                      ^
TypeError: Cannot read property 'replace' of undefined
    at _parseModuleResolutionError (/xdl/src/Project.js:920:23)
    at _logModuleResolutionError (/xdl/src/Project.js:963:44)
    at _logPackagerOutput (/xdl/src/Project.js:1012:5)
    at Socket.<anonymous> (/xdl/src/Project.js:1229:7)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

**Comment by arnoldbird** [comment]
Probably a duplicate of https://github.com/react-native-material-design/react-native-material-design/issues/174
